//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClienSubscriber.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/VelibLibrary")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableStandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalStandsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableStands {
            get {
                return this.AvailableStandsField;
            }
            set {
                if ((this.AvailableStandsField.Equals(value) != true)) {
                    this.AvailableStandsField = value;
                    this.RaisePropertyChanged("AvailableStands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalStands {
            get {
                return this.TotalStandsField;
            }
            set {
                if ((this.TotalStandsField.Equals(value) != true)) {
                    this.TotalStandsField = value;
                    this.RaisePropertyChanged("TotalStands");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo", Namespace="http://schemas.datacontract.org/2004/07/VelibLibrary")]
    [System.SerializableAttribute()]
    public partial class RequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CachedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cached {
            get {
                return this.CachedField;
            }
            set {
                if ((this.CachedField.Equals(value) != true)) {
                    this.CachedField = value;
                    this.RaisePropertyChanged("Cached");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Normal {
            get {
                return this.NormalField;
            }
            set {
                if ((this.NormalField.Equals(value) != true)) {
                    this.NormalField = value;
                    this.RaisePropertyChanged("Normal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Metrics", Namespace="http://schemas.datacontract.org/2004/07/VelibLibrary")]
    [System.SerializableAttribute()]
    public partial class Metrics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AvgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Avg {
            get {
                return this.AvgField;
            }
            set {
                if ((this.AvgField.Equals(value) != true)) {
                    this.AvgField = value;
                    this.RaisePropertyChanged("Avg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Max {
            get {
                return this.MaxField;
            }
            set {
                if ((this.MaxField.Equals(value) != true)) {
                    this.MaxField = value;
                    this.RaisePropertyChanged("Max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Min {
            get {
                return this.MinField;
            }
            set {
                if ((this.MinField.Equals(value) != true)) {
                    this.MinField = value;
                    this.RaisePropertyChanged("Min");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IVelib")]
    public interface IVelib {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelib/GetCities", ReplyAction="http://tempuri.org/IVelib/GetCitiesResponse")]
        string[] GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelib/GetCities", ReplyAction="http://tempuri.org/IVelib/GetCitiesResponse")]
        System.Threading.Tasks.Task<string[]> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelib/GetStations", ReplyAction="http://tempuri.org/IVelib/GetStationsResponse")]
        ConsoleClienSubscriber.ServiceReference.Station[] GetStations(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelib/GetStations", ReplyAction="http://tempuri.org/IVelib/GetStationsResponse")]
        System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.Station[]> GetStationsAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibChannel : ConsoleClienSubscriber.ServiceReference.IVelib, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibClient : System.ServiceModel.ClientBase<ConsoleClienSubscriber.ServiceReference.IVelib>, ConsoleClienSubscriber.ServiceReference.IVelib {
        
        public VelibClient() {
        }
        
        public VelibClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
        
        public ConsoleClienSubscriber.ServiceReference.Station[] GetStations(string city) {
            return base.Channel.GetStations(city);
        }
        
        public System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.Station[]> GetStationsAsync(string city) {
            return base.Channel.GetStationsAsync(city);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IMonitoring")]
    public interface IMonitoring {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoring/GetWSRequestsTimeSpan", ReplyAction="http://tempuri.org/IMonitoring/GetWSRequestsTimeSpanResponse")]
        ConsoleClienSubscriber.ServiceReference.RequestInfo GetWSRequestsTimeSpan(System.DateTime beg, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoring/GetWSRequestsTimeSpan", ReplyAction="http://tempuri.org/IMonitoring/GetWSRequestsTimeSpanResponse")]
        System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.RequestInfo> GetWSRequestsTimeSpanAsync(System.DateTime beg, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoring/GetWSRequests", ReplyAction="http://tempuri.org/IMonitoring/GetWSRequestsResponse")]
        ConsoleClienSubscriber.ServiceReference.RequestInfo GetWSRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoring/GetWSRequests", ReplyAction="http://tempuri.org/IMonitoring/GetWSRequestsResponse")]
        System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.RequestInfo> GetWSRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoring/GetMetrics", ReplyAction="http://tempuri.org/IMonitoring/GetMetricsResponse")]
        ConsoleClienSubscriber.ServiceReference.Metrics GetMetrics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoring/GetMetrics", ReplyAction="http://tempuri.org/IMonitoring/GetMetricsResponse")]
        System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.Metrics> GetMetricsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringChannel : ConsoleClienSubscriber.ServiceReference.IMonitoring, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringClient : System.ServiceModel.ClientBase<ConsoleClienSubscriber.ServiceReference.IMonitoring>, ConsoleClienSubscriber.ServiceReference.IMonitoring {
        
        public MonitoringClient() {
        }
        
        public MonitoringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleClienSubscriber.ServiceReference.RequestInfo GetWSRequestsTimeSpan(System.DateTime beg, System.DateTime end) {
            return base.Channel.GetWSRequestsTimeSpan(beg, end);
        }
        
        public System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.RequestInfo> GetWSRequestsTimeSpanAsync(System.DateTime beg, System.DateTime end) {
            return base.Channel.GetWSRequestsTimeSpanAsync(beg, end);
        }
        
        public ConsoleClienSubscriber.ServiceReference.RequestInfo GetWSRequests() {
            return base.Channel.GetWSRequests();
        }
        
        public System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.RequestInfo> GetWSRequestsAsync() {
            return base.Channel.GetWSRequestsAsync();
        }
        
        public ConsoleClienSubscriber.ServiceReference.Metrics GetMetrics() {
            return base.Channel.GetMetrics();
        }
        
        public System.Threading.Tasks.Task<ConsoleClienSubscriber.ServiceReference.Metrics> GetMetricsAsync() {
            return base.Channel.GetMetricsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IVelibEventContract", CallbackContract=typeof(ConsoleClienSubscriber.ServiceReference.IVelibEventContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IVelibEventContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibEventContract/Subscribe", ReplyAction="http://tempuri.org/IVelibEventContract/SubscribeResponse")]
        void Subscribe(string station, string city, int time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibEventContract/Subscribe", ReplyAction="http://tempuri.org/IVelibEventContract/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync(string station, string city, int time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibEventContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibEventContract/VelibChanged")]
        void VelibChanged(string station, string city, int Before, int After, int time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibEventContractChannel : ConsoleClienSubscriber.ServiceReference.IVelibEventContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibEventContractClient : System.ServiceModel.DuplexClientBase<ConsoleClienSubscriber.ServiceReference.IVelibEventContract>, ConsoleClienSubscriber.ServiceReference.IVelibEventContract {
        
        public VelibEventContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VelibEventContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VelibEventContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibEventContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibEventContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(string station, string city, int time) {
            base.Channel.Subscribe(station, city, time);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(string station, string city, int time) {
            return base.Channel.SubscribeAsync(station, city, time);
        }
    }
}
